-- MySQL Script generated by MySQL Workbench
-- Sun Sep 17 19:40:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ms_search_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ms_search_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_search_library` DEFAULT CHARACTER SET utf8 ;
USE `ms_search_library` ;

-- -----------------------------------------------------
-- Table `ms_search_library`.`MS_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ms_search_library`.`ms_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mz` DOUBLE NOT NULL,
  `rt` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
