-- MySQL Script generated by MySQL Workbench
-- Sat Sep 23 14:58:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ms_search_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ms_search_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ms_search_library` DEFAULT CHARACTER SET utf8 ;
USE `ms_search_library` ;

-- -----------------------------------------------------
-- Table `ms_search_library`.`compound_classification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ms_search_library`.`compound_classification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `kingdom` VARCHAR(255) NOT NULL,
  `superclass` VARCHAR(255) NULL,
  `class` VARCHAR(255) NULL,
  `subclass` VARCHAR(255) NULL,
  `direct_parent` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `direct_parent_UNIQUE` (`direct_parent` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ms_search_library`.`compound_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ms_search_library`.`compound_data` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `inchi_key` VARCHAR(255) NULL,
  `formula` VARCHAR(255) NOT NULL,
  `smile` VARCHAR(255) NULL,
  `cas` VARCHAR(255) NOT NULL,
  `exact_mass` DOUBLE NOT NULL,
  `mole_file` TEXT NOT NULL,
  `kind` VARCHAR(255) NULL,
  `pubchem_cid` BIGINT NOT NULL,
  `compound_classification_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `compound_classification_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `pubchem_cid_UNIQUE` (`pubchem_cid` ASC) VISIBLE,
  INDEX `fk_compound_data_compound_classification1_idx` (`compound_classification_id` ASC) VISIBLE,
  CONSTRAINT `fk_compound_data_compound_classification1`
    FOREIGN KEY (`compound_classification_id`)
    REFERENCES `ms_search_library`.`compound_classification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ms_search_library`.`spectrum_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ms_search_library`.`spectrum_data` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `precursor_mz` DOUBLE NOT NULL,
  `ms_level` INT NOT NULL,
  `ms2_spectrum` VARCHAR(10000) NULL,
  `last_modify` DATETIME NULL DEFAULT current_timestamp,
  `date_created` DATETIME NULL DEFAULT current_timestamp,
  `data_source` VARCHAR(100) NULL DEFAULT 'Unknow',
  `author_id` BIGINT NULL,
  `tool_type` VARCHAR(100) NOT NULL,
  `ion_mode` VARCHAR(45) NOT NULL,
  `tool_category` VARCHAR(255) NOT NULL,
  `collision_energy` DOUBLE NOT NULL DEFAULT 0.0,
  `precursor_type` VARCHAR(100) NOT NULL,
  `mz_error` DOUBLE NOT NULL,
  `compound_data_id` BIGINT NOT NULL,
  `compound_classification_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `compound_data_id`, `compound_classification_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_spectrum_data_compound_data_idx` (`compound_data_id` ASC) VISIBLE,
  INDEX `fk_spectrum_data_compound_classification1_idx` (`compound_classification_id` ASC) VISIBLE,
  CONSTRAINT `fk_spectrum_data_compound_data`
    FOREIGN KEY (`compound_data_id`)
    REFERENCES `ms_search_library`.`compound_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spectrum_data_compound_classification1`
    FOREIGN KEY (`compound_classification_id`)
    REFERENCES `ms_search_library`.`compound_classification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
